In [1]:
# import the wrapper
from mcmc import *
from power_spectra_1D import *
from power_spectra_2D import *

/home/tom/miniconda3/lib/python3.12/site-packages/py21cmfast/_cfg.py:57: UserWarning: Your configuration file is out of date. Updating...
  warnings.warn(
/home/tom/miniconda3/lib/python3.12/site-packages/py21cmfast/_cfg.py:41: UserWarning: Your configuration file is out of date. Updating...
  warnings.warn("Your configuration file is out of date. Updating...")
[potato:33530] shmem: mmap: an error occurred while determining whether or not /tmp/ompi.potato.1000/jf.0/3158441984/shared_mem_cuda_pool.potato could be created.
[potato:33530] create_and_attach: unable to create shared memory BTL coordinating structure :: size 134217728 


In [14]:
# w/o write: 
# w write: 

sim = Simulation(save_ondisk=False, save_inclass=True, write_cache=True, clean_cache=True)
# }
#{'ION_Tvir_MIN': 4.540949748007259, 'HII_EFF_FACTOR': 238.77818673489438, 'L_X': 39.63512786298546, 'NU_X_THRESH': 1156.8820204520493}
#params={'astro_params': {'ION_Tvir_MIN': 4.798687324224536, 'HII_EFF_FACTOR': 153.93554078107047, 'L_X': 41.07914816577325, 'NU_X_THRESH': 122.31064697905447}}

#{'astro_params': {'ION_Tvir_MIN': 4.7, 'HII_EFF_FACTOR': 30, 'L_X': 40, 'NU_X_THRESH': 500}}
sim.run_lightcone(kargs=params)




use astro_params default config: True
use cosmo_params default config: True
use user_params default config: False
use flag_options default config: False
use global_params default config: True
Using 21cmFAST version 3.3.1


In [15]:
#(array([ 9,  9,  9, 44, 44, 44]),
#array([68, 68, 68, 14, 14, 14]),
#array([ 62, 182, 302,  68, 188, 308]))
np.where(np.isnan(sim.data[0].brightness_temp)==True)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [4]:
from mcmc import *

init_params_ranges = {"astro_params": {"ION_Tvir_MIN": [4,5.3], "HII_EFF_FACTOR": [10, 250], 
                    "L_X": [38,42], "NU_X_THRESH": [100, 1500]}}

params={'astro_params': {'ION_Tvir_MIN': 4.7, 'HII_EFF_FACTOR': 30, 'L_X': 40, 'NU_X_THRESH': 500}}

def log_prior(theta):
        T_vir, H_eff, LX, nu_x = theta
        if 5 < H_eff < 250 and 100 < nu_x < 1500 and 4 < T_vir < 5.3 and 30 < LX < 50:
            return 0
        return - np.inf
    
def log_likelihood(t,f):
    return - np.sum((t - f)**2/(f+1))

mcrun = mcmc(nwalker=8, z_bins = 21, k_bins=np.linspace(5e-2,2.5,30), debug = True, log_likelihood=log_likelihood, prior=log_prior)
mcrun.make_fiducial(load = False, fparams=params)

#mcrun.run_aies(init_params_ranges)

use astro_params default config: True
use cosmo_params default config: True
use user_params default config: False
use flag_options default config: False
use global_params default config: True
Using 21cmFAST version 3.3.1


/home/tom/miniconda3/lib/python3.12/site-packages/py21cmfast/_utils.py:400: UserWarning: The following parameters to FlagOptions are not supported: ['USE_VELS_AUX']
  warnings.warn(
/home/tom/miniconda3/lib/python3.12/site-packages/py21cmfast/_utils.py:815: UserWarning: Trying to remove array that isn't yet created: lowres_density
  warnings.warn(f"Trying to remove array that isn't yet created: {k}")
/home/tom/miniconda3/lib/python3.12/site-packages/py21cmfast/_utils.py:815: UserWarning: Trying to remove array that isn't yet created: lowres_vx
  warnings.warn(f"Trying to remove array that isn't yet created: {k}")
/home/tom/miniconda3/lib/python3.12/site-packages/py21cmfast/_utils.py:815: UserWarning: Trying to remove array that isn't yet created: lowres_vy
  warnings.warn(f"Trying to remove array that isn't yet created: {k}")
/home/tom/miniconda3/lib/python3.12/site-packages/py21cmfast/_utils.py:815: UserWarning: Trying to remove array that isn't yet created: lowres_vz
  warnings.warn(

bin=0:  [[2.32310438 1.58180411 1.33448844 1.06157939 0.98120934 0.88931574
  0.84556732 0.80175759 0.79498928 0.82416388 0.80098511 0.80986259
  0.83345803 0.89257589 0.96239459 1.05806082 1.14759396 1.25671648
  1.38500929 1.46510825 1.61207802 1.74817615 1.93138088 2.10661517
  2.28045767 2.55929787 2.70289289 2.77871614 2.89551162]
 [0.1065747  0.18400635 0.26540151 0.34921829 0.43327635 0.5172451
  0.60145537 0.68542639 0.76965422 0.85419775 0.93840886 1.02259943
  1.10697484 1.1914598  1.2758823  1.36040212 1.44488954 1.52916866
  1.61257287 1.6968906  1.78112976 1.86555826 1.94966492 2.03367883
  2.11740029 2.20057267 2.28498055 2.36930255 2.45273921]]
bin=1:  [[ 8.20708059  5.27852719  4.81179222  3.98417275  3.51156038  3.20314266
   3.25281054  3.21830591  3.06017035  3.17528494  3.19349231  3.22365039
   3.44647316  3.65086032  3.95055664  4.16484168  4.54619166  5.07579609
   5.42727549  5.86427212  6.43413505  6.94036869  7.70934222  8.34544333
   9.23124585  9.85620598 10

In [ ]:
from p21cmfastwrapper import *

sim = Simulation(save_ondisk=True, save_inclass=False, write_cache=True, clean_cache=True)

args = {"M_WDM":[0.3,10.0],
                "astro_params": {"HII_EFF_FACTOR":[10,250],"L_X":[38,42],"NU_X_THRESH":[100,1500],"ION_Tvir_MIN":[4.0,5.3]},
                "cosmo_params": {"OMm":[0.2,0.4]}}
sim.run_samplef(nruns=50000, args=args=args, threads = 128)

In [ ]:
def fill_dict(nested_dict, array, index=0):
    """
    Fills the nested dictionary with elements from the array recursively.

    Parameters:
    nested_dict (dict): The nested dictionary to be filled.
    array (list): The list of elements to fill into the nested dictionary.
    index (int): The current index in the array.

    Returns:
    int: The next index to be used in the array.
    """
    for key in nested_dict:
        if isinstance(nested_dict[key], dict):
            index = fill_dict(nested_dict[key], array, index)
        else:
            if index < len(array):
                nested_dict[key] = array[index]
                index += 1
            else:
                break
    return nested_dict

In [ ]:
log_prior([  4.01547017, 245.68181515,  41.78008556, 142.73262024]) + log_likelihood(ps, mcrun.fid_ps) 

In [ ]:
from mcmc import *

init_params_ranges = {"astro_params": {"ION_Tvir_MIN": [4,5.3], "HII_EFF_FACTOR": [10, 250], 
                    "L_X": [38,42], "NU_X_THRESH": [100, 1500]}}

params={'astro_params': {'ION_Tvir_MIN': 4.7, 'HII_EFF_FACTOR': 30, 'L_X': 40, 'NU_X_THRESH': 500}}

def log_prior(theta):
        T_vir, H_eff, LX, nu_x = theta
        if 5 < H_eff < 250 and 100 < nu_x < 1500 and 4 < T_vir < 5.3 and 30 < LX < 50:
            return 0
        return - np.inf
    
def log_likelihood(t,f):
    return - np.sum((t - f)**2/(np.abs(f)+1))

mcrun = mcmc(nwalker=8, z_bins = 11, k_bins=30, debug = True, log_likelihood=log_likelihood, prior=log_prior)
mcrun.make_fiducial(load = True, fparams=params)

#mcrun.run_aies(init_params_ranges)

In [ ]:
from mcmc import *
init_params_ranges = {"astro_params": {"ION_Tvir_MIN": [4,5.3], "HII_EFF_FACTOR": [5, 100], 
                    "L_X": [30,50], "NU_X_THRESH": [100, 1500]}}

# input: init cube for parameter
def prior_sampling(theta):
        T_vir, H_eff, LX, nu_x = theta
        T_vir = 4 + 1.3*T_vir
        H_eff = 5 + 95*H_eff
        LX = 30 + 20*LX
        nu_x = 100 + 1400*nu_x
        return np.array([T_vir, H_eff, LX, nu_x])
    
# returns samples from the posterior
    
def log_likelihood(t,f):
    return - np.sum((t - f)**2/f)


mcrun = mcmc(z_bins = 11, debug = True, log_likelihood=log_likelihood, prior=prior_sampling)
mcrun.make_fiducial(load = True)

mcrun.run_ns(init_params_ranges)


In [ ]:
from mcmc import *
mcrun = mcmc(nwalker=8, z_bins = 11, debug = True, log_likelihood=log_likelihood, prior=log_prior)
mcrun.make_fiducial(load = False)

In [ ]:
import py21cmfast
py21cmfast.inputs.CosmoParams._defaults_

In [ ]:
args = {"astro_params": 
        {"NU_X_THRESH": [400,700], 
        "HII_EFF_FACTOR": [10,100],
        "L_X": [1,2],
        "ION_Tvir_MIN": [4,5]},
    "cosmo_params":
        {"OMm": [0,1]},
    "global_params": 
        {"M_WDM": [1,2]}}

In [ ]:
py21cmfast.inputs.global_params.M_WDM

In [ ]:
test = {"main": {"blub": 1, "blubber": 2}, "sek": {"schwubble": {"swap": 4}}}

In [ ]:
def extract_keys(nested_dict):
    keys = []
    for key in nested_dict:
        keys.append(key)
        if isinstance(nested_dict[key], dict):
            keys.extend(extract_keys(nested_dict[key]))
    return keys

In [ ]:
extract_keys(test)